name: Crystal CI

on:
  push:
  pull_request:

jobs:
  test_latest:
    runs-on: ubuntu-latest
    container:
      image: crystallang/crystal
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: shards install
      - name: Run tests
        run: crystal spec
